name: Java SDK Build JDK8

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_REPOSITORY: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B verify --file pom.xml
      - run: mkdir staging && cp client/target/*.jar staging
      - uses: actions/upload-artifact@v4
        with:
          name: kody-clientsdk-java6.jar
          path: |
            staging/*.jar
            !staging/original-*.jar
