name: Java SDK Build & Release JDK8

on:
  workflow_dispatch:

env:
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_REPOSITORY: ${{ github.repository }}
jobs:
  tagging:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
      version: ${{ steps.tag.outputs.version }}
      prerelease: ${{ steps.tag.outputs.prerelease }}
    steps:
      - name: Fetch head tag from kp-protocols-clientsdk
        id: tag
        run: |
          git clone --branch main https://github.com/KodyPay/kp-protocols-clientsdk.git proto-repo
          cd proto-repo
          head_tag=$(git describe --tags --exact-match HEAD 2>/dev/null || echo "")
          if [[ -z "${head_tag}" ]]; then
            echo "No tag found on the head commit of kp-protocols-clientsdk repo. Failing the action."
            exit 1
          else
            echo "tag=${head_tag}" >> $GITHUB_OUTPUT
            echo "version=${head_tag#v}" >> $GITHUB_OUTPUT
            if [[ "${head_tag}" == *-* ]]; then echo "prerelease=true" >> $GITHUB_OUTPUT; else echo "prerelease=false" >> $GITHUB_OUTPUT; fi
          fi

  publish:
    needs:
      - tagging
    runs-on: ubuntu-latest
    outputs:
      artifact: ${{ steps.artifact-upload-step.outputs.artifact-url }}
    env:
      MAVEN_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_PROJECT_mavenCentralUsername }}
      MAVEN_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_PROJECT_mavenCentralPassword }}
      MAVEN_PROJECT_signingInMemoryKeyPassphrase: ${{ secrets.MAVEN_PROJECT_signingInMemoryKeyPassphrase }}
      MAVEN_PROJECT_signingInMemoryKey: ${{ secrets.MAVEN_PROJECT_signingInMemoryKey }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'maven'
          server-id: central
          server-username: MAVEN_PROJECT_mavenCentralUsername
          server-password: MAVEN_PROJECT_mavenCentralPassword
          gpg-passphrase: MAVEN_PROJECT_signingInMemoryKeyPassphrase
          gpg-private-key: ${{ secrets.MAVEN_PROJECT_signingInMemoryKey }}
      - name: Build with Maven
        run: mvn -B verify --file pom.xml
      - name: Setup git config
        run: |
          echo "Setting up Git user information"
          git config --global user.name "${{github.actor}}"
          git config --global user.email "<>"
      - name: Set version
        run: mvn -B versions:set -DnewVersion=${{ needs.tagging.outputs.version }} -DgenerateBackupPoms=false
      - name: Publish release
        run: mvn -B deploy -Prelease --file client/pom.xml --settings $HOME/.m2/settings.xml
      - run: mkdir staging && cp client/target/*.jar staging
      - name: Upload artifact
        id: artifact-upload-step
        uses: actions/upload-artifact@v4.4.3
        with:
          name: kody-clientsdk-java6.jar
          path: |
            staging/*.jar
            !staging/original-*.jar

  release:
    needs:
      - tagging
      - publish
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          name: "${{ needs.tagging.outputs.tag }}"
          tag: "${{ needs.tagging.outputs.tag }}"
          omitBody: true
          draft: false
          makeLatest: true
          artifacts: ${{ needs.publish.outputs.artifact }}
